-- MySQL Script generated by MySQL Workbench
-- Thu Jan  8 20:56:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brasileirao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `brasileirao` ;

-- -----------------------------------------------------
-- Schema brasileirao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brasileirao` DEFAULT CHARACTER SET utf8 ;
USE `brasileirao` ;

-- -----------------------------------------------------
-- Table `brasileirao`.`cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`cartao` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`cartao` (
  `car_serie` CHAR(1) NOT NULL,
  `car_ano` INT NOT NULL,
  `clube_clu_sigla` CHAR(3) NOT NULL,
  `car_qtd_vermelho` INT NULL,
  `car_qtd_amarelo` INT NULL,
  PRIMARY KEY (`car_serie`, `car_ano`, `clube_clu_sigla`))
ENGINE = InnoDB;

CREATE INDEX `fk_cartao_clube1_idx` ON `brasileirao`.`cartao` (`clube_clu_sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`cidade` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`cidade` (
  `cid_id` INT NOT NULL,
  `cid_nome` VARCHAR(100) NOT NULL,
  `cid_uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`cid_id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `brasileirao`.`classificacao_geral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`classificacao_geral` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`classificacao_geral` (
  `clg_id` INT NOT NULL,
  `clg_serie` CHAR(1) NOT NULL,
  `clg_ano` INT NOT NULL,
  `clg_pontos` INT NOT NULL,
  `clg_vitorias` INT NOT NULL,
  `clg_saldo_gols` INT NOT NULL,
  `clg_gols_pro` INT NOT NULL,
  `clg_confronto_direto` INT NOT NULL,
  `clg_vermelho_clube_clu_sigla` CHAR(3) NOT NULL,
  `clg_amarelo_clube_clu_sigla` CHAR(3) NOT NULL,
  `clube__clu_sigla` CHAR(3) NOT NULL,
  `clg_qtd_jogou` INT NULL,
  `clg_qtd_empates` INT NULL,
  `clg_qtd_derrotas` INT NULL,
  `clg_gols_contra` INT NULL,
  PRIMARY KEY (`clg_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_classificacao_clube1_idx` ON `brasileirao`.`classificacao_geral` (`clube__clu_sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`classificacao_rodada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`classificacao_rodada` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`classificacao_rodada` (
  `clr_id` INT NOT NULL,
  `clr_serie` CHAR(1) NOT NULL,
  `clr_ano` INT NOT NULL,
  `clr_rodada` VARCHAR(45) NULL,
  `clr_pontos` INT NOT NULL,
  `clr_vitorias` INT NOT NULL,
  `clr_saldo_gols` INT NOT NULL,
  `clr_gols_pro` INT NOT NULL,
  `clr_confronto_direto` INT NOT NULL,
  `clr_vermelho_clube_clu_sigla` CHAR(3) NOT NULL,
  `clr_amarelo_clube_clu_sigla` CHAR(3) NOT NULL,
  `clube_clu_sigla` CHAR(3) NOT NULL,
  `clr_qtd_jogou` INT NULL,
  `clr_qtd_empates` INT NULL,
  `clr_qtd_derrotas` INT NULL,
  `clr_gols_contra` INT NULL,
  PRIMARY KEY (`clr_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_classificacao_clube1_idx` ON `brasileirao`.`classificacao_rodada` (`clube_clu_sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`clube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`clube` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`clube` (
  `clu_sigla` CHAR(3) NOT NULL,
  `clu_nome` VARCHAR(60) NOT NULL,
  `clu_serie` CHAR(1) NOT NULL,
  `clu_link_escudo` VARCHAR(100) NOT NULL,
  `cidade_cid_id` INT NOT NULL,
  PRIMARY KEY (`clu_sigla`, `cidade_cid_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_clube_cidade_idx` ON `brasileirao`.`clube` (`cidade_cid_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`estadio` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`estadio` (
  `est_id` INT NOT NULL,
  `est_nome` VARCHAR(100) NOT NULL,
  `cidade_cid_id` INT NOT NULL,
  PRIMARY KEY (`est_id`, `cidade_cid_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_estadio_cidade1_idx` ON `brasileirao`.`estadio` (`cidade_cid_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`parametro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`parametro` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`parametro` (
  `par_id` INT NOT NULL,
  `par_serie` CHAR(1) NOT NULL,
  `par_ano` INT NOT NULL,
  PRIMARY KEY (`par_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brasileirao`.`rodada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`rodada` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`rodada` (
  `rod_serie` CHAR(1) NOT NULL,
  `rod_ano` INT NOT NULL,
  `rod_rodada` INT NOT NULL,
  `rod_sequencia` INT NOT NULL,
  `rod_data` DATETIME NOT NULL,
  `clube_clu_sigla_mandante` CHAR(3) NOT NULL,
  `rod_gols_mandante` INT NULL,
  `clube_clu_sigla_visitante` CHAR(3) NOT NULL,
  `rod_gols_visitante` INT NULL,
  `rod_pontos_mandante` INT NULL,
  `rod_pontos_visitante` INT NULL,
  `rod_qdt_vermelho` INT NULL,
  `rod_qtd_amarelo` INT NULL,
  `rod_calculou_classificacao` CHAR(1) NULL DEFAULT '\"N\", \"S\"',
  `rod_partida_finalidaza` CHAR(1) NULL DEFAULT '\"N\", \"S\"',
  PRIMARY KEY (`rod_serie`, `rod_ano`, `rod_rodada`, `rod_sequencia`))
ENGINE = InnoDB;

CREATE INDEX `fk_rodada_clube1_idx` ON `brasileirao`.`rodada` (`clube_clu_sigla_mandante` ASC) VISIBLE;

CREATE INDEX `fk_rodada_clube2_idx` ON `brasileirao`.`rodada` (`clube_clu_sigla_visitante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`usuario` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`usuario` (
  `usu_id` INT NOT NULL,
  `usu_nome` VARCHAR(100) NOT NULL,
  `usu_email` VARCHAR(100) NOT NULL,
  `usu_senha` VARCHAR(100) NOT NULL,
  `usu_ativo` BOOLEAN NOT NULL,
  `usu_admin` BOOLEAN NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
