-- MySQL Script generated by MySQL Workbench
-- Wed Dec 24 11:36:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brasileirao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `brasileirao` ;

-- -----------------------------------------------------
-- Schema brasileirao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brasileirao` DEFAULT CHARACTER SET utf8 ;
USE `brasileirao` ;

-- -----------------------------------------------------
-- Table `brasileirao`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`cidade` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`cidade` (
  `cid_id` INT NOT NULL AUTO_INCREMENT,
  `cid_nome` VARCHAR(100) NOT NULL,
  `cid_uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`cid_id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `brasileirao`.`classificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`classificacao` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`classificacao` (
  `cla_id` INT NOT NULL AUTO_INCREMENT,
  `cla_serie` CHAR(1) NOT NULL,
  `cla_ano` INT NOT NULL,
  `cla_pontos` INT NOT NULL,
  `cla_vitorias` INT NOT NULL,
  `cla_saldo_gols` INT NOT NULL,
  `cla_gols_pro` INT NOT NULL,
  `cla_confronto_direto` INT NOT NULL,
  `vermelho_clube_clu_sigla` CHAR(3) NOT NULL,
  `amarelo_clube_clu_sigla` CHAR(3) NOT NULL,
  `clube_clu_sigla` CHAR(3) NOT NULL,
  `cla_qtd_jogou` INT NULL,
  `cla_qtd_empates` INT NULL,
  `cla_qtd_derrotas` INT NULL,
  `cla_gols_contra` INT NULL,
  PRIMARY KEY (`cla_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_classificacao_clube1_idx` ON `brasileirao`.`classificacao` (`clube_clu_sigla` ASC) VISIBLE;

CREATE INDEX idx_classificacao_pontos 
ON `brasileirao`.classificacao (
    `cla_serie` ASC, 
    `cla_ano`ASC, 
    `cla_pontos` DESC, 
    `cla_vitorias` DESC, 
    `cla_saldo_gols` DESC, 
    `cla_gols_pro` DESC, 
    `cla_confronto_direto` DESC, 
    `vermelho_clube_clu_sigla` ASC, 
    `amarelo_clube_clu_sigla` ASC
);

-- -----------------------------------------------------
-- Table `brasileirao`.`clube`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`clube` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`clube` (
  `clu_sigla` CHAR(3) NOT NULL,
  `clu_nome` VARCHAR(60) NOT NULL,
  `clu_link_escudo` VARCHAR(100) NOT NULL,
  `cidade_cid_id` INT NOT NULL,
  PRIMARY KEY (`clu_sigla`, `cidade_cid_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_clube_cidade_idx` ON `brasileirao`.`clube` (`cidade_cid_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`estadio` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`estadio` (
  `est_id` INT NOT NULL AUTO_INCREMENT,
  `est_nome` VARCHAR(100) NOT NULL,
  `cidade_cid_id` INT NOT NULL,
  PRIMARY KEY (`est_id`, `cidade_cid_id`))
ENGINE = InnoDB;

CREATE INDEX `fk_estadio_cidade1_idx` ON `brasileirao`.`estadio` (`cidade_cid_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `brasileirao`.`rodada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brasileirao`.`rodada` ;

CREATE TABLE IF NOT EXISTS `brasileirao`.`rodada` (
  `rod_serie` CHAR(1) NOT NULL,
  `rod_ano` INT NOT NULL,
  `rod_rodada` INT NOT NULL,
  `rod_sequencia` INT NOT NULL,
  `rod_data` DATETIME NOT NULL,
  `clube_clu_sigla_mandante` CHAR(3) NOT NULL,
  `rod_gols_mandante` INT NULL,
  `clube_clu_sigla_visitante` CHAR(3) NOT NULL,
  `rod_gols_visitante` INT NULL,
  `rod_pontos_mandante` INT NULL,
  `rod_pontos_visitante` INT NULL,
  `rod_qdt_vermelho` INT NULL,
  `rod_qtd_amarelo` INT NULL,
  `rod_calculou_classificacao` CHAR(1) NULL DEFAULT 'N',
  `rod_partida_finalidaza` CHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`rod_serie`, `rod_ano`, `rod_rodada`, `rod_sequencia`))
ENGINE = InnoDB;

CREATE INDEX `fk_rodada_clube1_idx` ON `brasileirao`.`rodada` (`clube_clu_sigla_mandante` ASC) VISIBLE;

CREATE INDEX `fk_rodada_clube2_idx` ON `brasileirao`.`rodada` (`clube_clu_sigla_visitante` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
