"""altera classif geral e por rodada

Revision ID: 1a65e99a0ec9
Revises: e8130c11a669
Create Date: 2026-09-02 20:55:10.039293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a65e99a0ec9'
down_revision: Union[str, Sequence[str], None] = 'e8130c11a669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classificacao_geral', sa.Column('car_qtd_vermelho', sa.Integer(), nullable=True))
    op.add_column('classificacao_geral', sa.Column('car_qtd_amarelo', sa.Integer(), nullable=True))
    op.add_column('classificacao_rodada', sa.Column('car_qtd_vermelho', sa.Integer(), nullable=True))
    op.add_column('classificacao_rodada', sa.Column('car_qtd_amarelo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classificacao_rodada', 'car_qtd_amarelo')
    op.drop_column('classificacao_rodada', 'car_qtd_vermelho')
    op.drop_column('classificacao_geral', 'car_qtd_amarelo')
    op.drop_column('classificacao_geral', 'car_qtd_vermelho')
    # ### end Alembic commands ###
