"""Initial Migration

Revision ID: bc8828d4e960
Revises: 
Create Date: 2026-01-13 18:28:01.436903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8828d4e960'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidade',
    sa.Column('cid_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cid_nome', sa.String(length=100), nullable=False),
    sa.Column('cid_uf', sa.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('cid_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadio',
    sa.Column('est_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('est_nome', sa.String(length=100), nullable=False),
    sa.Column('cidade_cid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_cid_id'], ['cidade.cid_id'], ),
    sa.PrimaryKeyConstraint('est_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadio')
    op.drop_table('usuario')
    op.drop_table('cidade')
    # ### end Alembic commands ###
