"""Initial schema

Revision ID: e71ea39b41f5
Revises: 
Create Date: 2026-01-28 17:07:53.777023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71ea39b41f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidade',
    sa.Column('cid_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cid_nome', sa.String(length=100), nullable=False),
    sa.Column('cid_uf', sa.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('cid_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clube',
    sa.Column('clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clu_nome', sa.String(length=60), nullable=False),
    sa.Column('clu_serie', sa.CHAR(length=1), nullable=False),
    sa.Column('clu_link_escudo', sa.String(length=100), nullable=False),
    sa.Column('cidade_cid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_cid_id'], ['cidade.cid_id'], ),
    sa.PrimaryKeyConstraint('clu_sigla')
    )
    op.create_table('estadio',
    sa.Column('est_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('est_nome', sa.String(length=100), nullable=False),
    sa.Column('cidade_cid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_cid_id'], ['cidade.cid_id'], ),
    sa.PrimaryKeyConstraint('est_id')
    )
    op.create_table('cartao',
    sa.Column('car_serie', sa.CHAR(length=1), nullable=False),
    sa.Column('car_ano', sa.Integer(), nullable=False),
    sa.Column('clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('car_qtd_vermelho', sa.Integer(), nullable=True),
    sa.Column('car_qtd_amarelo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.PrimaryKeyConstraint('car_serie', 'car_ano', 'clube_clu_sigla')
    )
    op.create_table('classificacao_geral',
    sa.Column('clg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clg_serie', sa.CHAR(length=1), nullable=False),
    sa.Column('clg_ano', sa.Integer(), nullable=False),
    sa.Column('clg_pontos', sa.Integer(), nullable=False),
    sa.Column('clg_vitorias', sa.Integer(), nullable=False),
    sa.Column('clg_saldo_gols', sa.Integer(), nullable=False),
    sa.Column('clg_gols_pro', sa.Integer(), nullable=False),
    sa.Column('clg_confronto_direto', sa.Integer(), nullable=False),
    sa.Column('clg_vermelho_clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clg_amarelo_clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clg_qtd_jogou', sa.Integer(), nullable=True),
    sa.Column('clg_qtd_empates', sa.Integer(), nullable=True),
    sa.Column('clg_qtd_derrotas', sa.Integer(), nullable=True),
    sa.Column('clg_gols_contra', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clg_amarelo_clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.ForeignKeyConstraint(['clg_vermelho_clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.ForeignKeyConstraint(['clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.PrimaryKeyConstraint('clg_id')
    )
    op.create_table('classificacao_rodada',
    sa.Column('clr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clr_serie', sa.CHAR(length=1), nullable=False),
    sa.Column('clr_ano', sa.Integer(), nullable=False),
    sa.Column('clr_rodada', sa.String(length=45), nullable=True),
    sa.Column('clr_pontos', sa.Integer(), nullable=False),
    sa.Column('clr_vitorias', sa.Integer(), nullable=False),
    sa.Column('clr_saldo_gols', sa.Integer(), nullable=False),
    sa.Column('clr_gols_pro', sa.Integer(), nullable=False),
    sa.Column('clr_confronto_direto', sa.Integer(), nullable=False),
    sa.Column('clr_vermelho_clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clr_amarelo_clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clube_clu_sigla', sa.CHAR(length=3), nullable=False),
    sa.Column('clr_qtd_jogou', sa.Integer(), nullable=True),
    sa.Column('clr_qtd_empates', sa.Integer(), nullable=True),
    sa.Column('clr_qtd_derrotas', sa.Integer(), nullable=True),
    sa.Column('clr_gols_contra', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clr_amarelo_clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.ForeignKeyConstraint(['clr_vermelho_clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.ForeignKeyConstraint(['clube_clu_sigla'], ['clube.clu_sigla'], ),
    sa.PrimaryKeyConstraint('clr_id')
    )
    op.create_table('rodada',
    sa.Column('rod_serie', sa.CHAR(length=1), nullable=False),
    sa.Column('rod_ano', sa.Integer(), nullable=False),
    sa.Column('rod_rodada', sa.Integer(), nullable=False),
    sa.Column('rod_sequencia', sa.Integer(), nullable=False),
    sa.Column('rod_data', sa.DATETIME(), nullable=False),
    sa.Column('clube_clu_sigla_mandante', sa.CHAR(length=3), nullable=False),
    sa.Column('rod_gols_mandante', sa.Integer(), nullable=True),
    sa.Column('clube_clu_sigla_visitante', sa.CHAR(length=3), nullable=False),
    sa.Column('rod_gols_visitante', sa.Integer(), nullable=True),
    sa.Column('rod_pontos_mandante', sa.Integer(), nullable=True),
    sa.Column('rod_pontos_visitante', sa.Integer(), nullable=True),
    sa.Column('rod_calculou_classificacao', sa.CHAR(length=1), nullable=True),
    sa.Column('rod_partida_finalidaza', sa.CHAR(length=1), nullable=True),
    sa.Column('estadio_est_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clube_clu_sigla_mandante'], ['clube.clu_sigla'], ),
    sa.ForeignKeyConstraint(['clube_clu_sigla_visitante'], ['clube.clu_sigla'], ),
    sa.ForeignKeyConstraint(['estadio_est_id'], ['estadio.est_id'], ),
    sa.PrimaryKeyConstraint('rod_serie', 'rod_ano', 'rod_rodada', 'rod_sequencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rodada')
    op.drop_table('classificacao_rodada')
    op.drop_table('classificacao_geral')
    op.drop_table('cartao')
    op.drop_table('estadio')
    op.drop_table('clube')
    op.drop_table('usuario')
    op.drop_table('cidade')
    # ### end Alembic commands ###
