"""index por id cidade

Revision ID: e8130c11a669
Revises: 153de0ecc709
Create Date: 2026-08-02 15:15:11.054200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8130c11a669'
down_revision: Union[str, Sequence[str], None] = '153de0ecc709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_clube_cidade_cid_id', 'clube', ['cidade_cid_id'], unique=False)
    op.create_index('idx_estadio_cidade_cid_id', 'estadio', ['cidade_cid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_estadio_cidade_cid_id', table_name='estadio')
    op.drop_index('idx_clube_cidade_cid_id', table_name='clube')
    # ### end Alembic commands ###
